# Generated by Django 5.2.1 on 2025-05-20 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='done_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailygoalstatus',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_statuses', to='objectives.goal'),
        ),
    ]
