# Generated by Django 5.2.1 on 2025-05-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.IntegerField(blank=True),
        ),
    ]
