# Generated by Django 5.2.1 on 2025-05-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievments', '0002_alter_achievement_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='points_needed',
            field=models.IntegerField(default=100),
        ),
    ]
