# Generated by Django 5.2.1 on 2025-05-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievments', '0003_achievement_points_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(blank=True),
        ),
    ]
