# Generated by Django 5.2.1 on 2025-05-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievments', '0004_alter_achievement_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.IntegerField(default=0),
        ),
    ]
